DROP TABLE ALTPAIR;
DROP TABLE GROUPCHATS;
DROP TABLE PAIRLINKS;
DROP TABLE STAROSTA;
DROP TABLE STUDENTS;
DROP TABLE GROUPS;

CREATE TABLE GROUPS(
    ID BIGSERIAL,
    NAME VARCHAR,
    PRIMARY KEY(ID)
);

CREATE TABLE STUDENTS(
    ID BIGINT, -- USER TELEGRAM ID
    GRP_ID BIGINT,
    PRIMARY KEY(ID)
);

CREATE TABLE STAROSTA(
    STD_ID BIGINT,
    GRP_ID BIGINT,
    PRIMARY KEY(STD_ID, GRP_ID)
);

CREATE TABLE PAIRLINKS(
    DSC_ID BIGINT, --KOD_DISC
    GRP_ID BIGINT,
    DSC_TYPE INT, --TYPE DISC: None, lec, lab ...
    LINK TEXT,
    LINK_ID TEXT, --ZOOM ID
    PASS TEXT, --ZOOM PASS
    PRIMARY KEY(DSC_ID, GRP_ID, DSC_TYPE)
);

CREATE TABLE GROUPCHATS(
    ID BIGINT, --TELEGRAM CHAT ID
    GRP_ID BIGINT, 
    PRIMARY KEY(ID)
);

CREATE TABLE ALTPAIR(
    DATE_REG DATE,
    NUM_PAIR INT,
    GRP_ID BIGINT,
    INFO TEXT,
    PRIMARY KEY(DATE_REG, NUM_PAIR, GRP_ID)
);

ALTER TABLE STUDENTS ADD FOREIGN KEY(GRP_ID) REFERENCES GROUPS(ID);
ALTER TABLE STAROSTA ADD FOREIGN KEY(STD_ID) REFERENCES STUDENTS(ID);
ALTER TABLE STAROSTA ADD FOREIGN KEY(GRP_ID) REFERENCES GROUPS(ID);
ALTER TABLE PAIRLINKS ADD FOREIGN KEY(GRP_ID) REFERENCES GROUPS(ID);
ALTER TABLE GROUPCHATS ADD FOREIGN KEY(GRP_ID) REFERENCES GROUPS(ID);
ALTER TABLE ALTPAIR ADD FOREIGN KEY(GRP_ID) REFERENCES GROUPS(ID);